### ISSUE TITLE
haproxy.syslog.amzn2': No such file or directory

### ISSUE THREAD

**Issue by npoojary** [philyuchkoff/HAProxy-3-RPM-builder#1]
I tried to RPM builder for HAProxy 3.0 using YUM but ended up with below error. Please help. 

Platform 

uname -a
Linux testamilb101 5.10.223-211.872.amzn2.x86_64 #1 SMP Mon Jul 29 19:52:29 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

error 

+ cd haproxy-3.0.3
+ '[' /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64 '!=' / ']'
+ /usr/bin/rm -rf /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/usr/sbin
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/usr/bin
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/haproxy
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/haproxy/errors
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/usr/share/man/man1/
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/logrotate.d
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/rsyslog.d
+ /usr/bin/install -d /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/var/log/haproxy
+ /usr/bin/install -s haproxy /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/usr/sbin/
+ /usr/bin/install -c -m 644 /opt/HAProxy-3-RPM-builder/rpmbuild/SOURCES/haproxy.cfg /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/haproxy/haproxy.cfg
+ /usr/bin/install -c -m 644 examples/errorfiles/400.http examples/errorfiles/403.http examples/errorfiles/408.http examples/errorfiles/500.http examples/errorfiles/502.http examples/errorfiles/503.http examples/errorfiles/504.http /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/haproxy/errors/
+ /usr/bin/install -c -m 644 doc/haproxy.1 /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/usr/share/man/man1/
+ /usr/bin/install -c -m 644 /opt/HAProxy-3-RPM-builder/rpmbuild/SOURCES/haproxy.syslog.amzn2 /opt/HAProxy-3-RPM-builder/rpmbuild/BUILDROOT/haproxy-3.0.3-1.x86_64/etc/rsyslog.d/49-haproxy.conf
/usr/bin/install: cannot stat '/opt/HAProxy-3-RPM-builder/rpmbuild/SOURCES/haproxy.syslog.amzn2': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.jQHnWn (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.jQHnWn (%install)
make: *** [build] Error 1

**Comment by philyuchkoff** [comment]
Files added, check, plz

**Comment by npoojary** [comment]
Thank you so much. It's working.

haproxy -vvv
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 5.10.223-211.872.amzn2.x86_64 #1 SMP Mon Jul 29 19:52:29 UTC 2024 x86_64
