### ISSUE TITLE
haproxy not starting with systemd

### ISSUE THREAD

**Issue by Shaoranlaos** [philyuchkoff/HAProxy-3-RPM-builder#2]
The systemd service by the generated RPM can not start the haproxy because of the missing Master-Worker (-Ws) parameter in the config check (ExecStartPre).
This is also the case for the ExecReload.

Error from systemctl status:
````
haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/haproxy.service.d
           └─override.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2024-10-25 12:52:45 CEST; 836ms ago
     Docs: man:haproxy(1)
  Process: 410076 ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS (code=exited, status=0/SUCCESS)
  Process: 412772 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=1/FAILURE)
 Main PID: 410076 (code=exited, status=0/SUCCESS)

Oct 25 12:52:45 XXX systemd[1]: haproxy.service: Control process exited, code=exited status=1
Oct 25 12:52:45 XXX systemd[1]: haproxy.service: Failed with result 'exit-code'.
Oct 25 12:52:45 XXX systemd[1]: Failed to start HAProxy Load Balancer.

````

Corrected Systemd Service:
...
ExecStartPre=/usr/sbin/haproxy -Ws -f $CONFIG -c -q $EXTRAOPTS
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
ExecReload=/usr/sbin/haproxy -Ws -f $CONFIG -c -q $EXTRAOPTS
...

With this the haproxy is correctly starting.

Why the same file is working in 2.X  ([HAProxy-2-RPM-builder](https://github.com/philyuchkoff/HAProxy-2-RPM-builder)) is unknown ...

**Comment by philyuchkoff** [comment]
@Shaoranlaos 
Thanks for the error found, I fixed it in [this](https://github.com/philyuchkoff/HAProxy-3-RPM-builder/commit/1f91f6d4658ad5e99da2011e78d2a65b16766929) commit.
